//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RA76154Entities : DbContext
    {
        public RA76154Entities()
            : base("name=RA76154Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FormaPagamento> FormaPagamento { get; set; }
        public virtual DbSet<Operadora> Operadora { get; set; }
        public virtual DbSet<Recarga> Recarga { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
    }
}
